# Generated by Django 5.1.3 on 2024-11-29 12:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer_manager', 'Customer Manager'), ('ticket_manager', 'Ticket Manager'), ('sales_manager', 'Sales Manager'), ('asset_manager', 'Asset Manager'), ('warehouse_manager', 'Warehouse Manager'), ('finance_manager', 'Finance Manager'), ('user', 'User'),  ('third_party', 'Third Party') ], default='user', max_length=20),
        ),
    ]

