#version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "55432:5432"  # Expose for external tools if needed
    networks:
      - asset_management_network

  backend:
    build:
      context: ./backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    ports:
      - "8800:8000"
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - asset_management_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4300:3000"
    networks:
      - asset_management_network

networks:
  asset_management_network:
    external: true